
SELECT *
FROM (
    SELECT
        TO_CHAR(ONS.SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE,
        ONS.PRODUCT_ID,
        ONS.USER_ID,
        ONS.SALES_AMOUNT
    FROM ONLINE_SALE ONS
    WHERE TO_CHAR(ONS.SALES_DATE, 'YYYYMM') = '202203'
    UNION ALL
    SELECT
        TO_CHAR(OFFS.SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE,
        OFFS.PRODUCT_ID,
        NULL AS USER_ID,
        OFFS.SALES_AMOUNT
    FROM OFFLINE_SALE OFFS
    WHERE TO_CHAR(OFFS.SALES_DATE, 'YYYYMM') = '202203') T
ORDER BY T.SALES_DATE, T.PRODUCT_ID, T.USER_ID;
