SELECT T.FLAVOR
FROM (
    SELECT
        FH.FLAVOR,
        SUM(FH.TOTAL_ORDER) AS TOTAL_ORDER
    FROM FIRST_HALF FH
        INNER JOIN ICECREAM_INFO II
        ON FH.FLAVOR = II.FLAVOR
    WHERE II.INGREDIENT_TYPE = 'fruit_based'
    GROUP BY FH.FLAVOR) T
WHERE T.TOTAL_ORDER > 3000
ORDER BY TOTAL_ORDER DESC;