SELECT
    T.HOUR,
    COUNT(AO.ANIMAL_ID) AS COUNT
FROM (
    SELECT
        LEVEL - 1 AS HOUR
    FROM DUAL
    CONNECT BY LEVEL <= 24) T
    LEFT JOIN ANIMAL_OUTS AO ON T.HOUR = TO_CHAR(AO.DATETIME, 'HH24')
GROUP BY T.HOUR
ORDER BY T.HOUR;