SELECT *
FROM (
    SELECT
        AI.NAME,
        AI.DATETIME
    FROM ANIMAL_INS AI
    WHERE NOT EXISTS (
        SELECT *
        FROM ANIMAL_OUTS AO
        WHERE AO.ANIMAL_ID = AI.ANIMAL_ID)
    ORDER BY AI.DATETIME) T
WHERE ROWNUM <= 3;