SELECT P.ID, P.NAME, P.HOST_ID
FROM PLACES P
    INNER JOIN (
    SELECT
        HOST_ID,
        COUNT(*) AS COUNT
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(*) >= 2) T
    ON P.HOST_ID = T.HOST_ID
ORDER BY ID
;