SELECT
    REST_ID,
    REST_NAME,
    FOOD_TYPE,
    FAVORITES, 
    ADDRESS,
    SCORE
FROM (
    SELECT
        RI.REST_ID,
        RI.REST_NAME,
        RI.FOOD_TYPE,
        RI.FAVORITES, 
        RI.ADDRESS,
        ROUND(AVG(NVL(RR.REVIEW_SCORE, 0)), 2) AS SCORE
    FROM REST_INFO RI
        Inner JOIN REST_REVIEW RR ON RI.REST_ID = RR.REST_ID
    WHERE RI.ADDRESS LIKE '서울%'
    GROUP BY
        RI.REST_ID,
        RI.REST_NAME,
        RI.FOOD_TYPE,
        RI.FAVORITES,
        RI.ADDRESS) T
ORDER BY SCORE DESC, FAVORITES DESC;